title: YVers Hardscaping
email: yurekvers@gmail.com
author: Yurek Vers
description: >-
  Professional interlocking stone installers creating pathways, driveways, entraces, patios and more,
  serving Guelph, Georgetown, Rockwood, Acton, Kitchener and area.
baseurl: ""
url: "https://yvershardscaping.com"
lang: en_CA
google_analytics: UA-117997684-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
source: src
destination: dist
sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - app
