title: YVers Hardscaping
email: yurekvers@gmail.com
author: Yurek Vers
description: >-
  Professional interlocking stone installers creating pathways, driveways, entraces, patios and more.
  Serving Guelph, Georgetown, Rockwood, Acton, Kitchener and area in Ontario, Canada.
baseurl: ""
url: "https://yvershardscaping.com"
lang: en_CA
google_analytics: UA-117997684-1

# Info
georgetown_phone: (416) 606 7337
guelph_phone: (519) 731 5273

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
source: src
destination: dist

# Custom
thumbnail_width: 120
thumbnail_height: 90
image_separator: __

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - app
